build.gradle
src/main/java/com/freepath/devpath/command/controller/UserCommandController.java
src/main/java/com/freepath/devpath/command/entity/User.java
src/main/java/com/freepath/devpath/command/entity/UserRole.java
src/main/java/com/freepath/devpath/command/repository/UserRepository.java
src/main/java/com/freepath/devpath/command/service/UserCommandService.java
src/main/java/com/freepath/devpath/common/config/SecurityConfig.java
src/main/java/com/freepath/devpath/common/dto/UserCreateRequest.java
src/main/java/com/freepath/devpath/common/jwt/RestAccessDeniedHandler.java
src/main/java/com/freepath/devpath/common/jwt/RestAuthenticationEntryPoint.java
src/main/java/com/freepath/devpath/common/response/ApiResponse.java
src/main/resources/application.yml

feat: 유저 회원가입 기능 구현

---

src/main/java/com/freepath/devpath/command/entity/UserRole.java
src/main/java/com/freepath/devpath/common/auth/controller/AuthController.java
src/main/java/com/freepath/devpath/common/auth/dto/LoginRequest.java
src/main/java/com/freepath/devpath/common/auth/dto/RefreshTokenRequest.java
src/main/java/com/freepath/devpath/common/auth/dto/TokenResponse.java
src/main/java/com/freepath/devpath/common/auth/entity/RefreshToken.java
src/main/java/com/freepath/devpath/common/auth/repository/RefreshTokenRepository.java
src/main/java/com/freepath/devpath/common/auth/service/AuthService.java
src/main/java/com/freepath/devpath/common/auth/service/CustomUserDetailsService.java
src/main/java/com/freepath/devpath/common/config/RedisConfig.java
src/main/java/com/freepath/devpath/common/config/SecurityConfig.java
src/main/java/com/freepath/devpath/common/jwt/JwtAuthenticationFilter.java
src/main/java/com/freepath/devpath/common/jwt/JwtTokenProvider.java
src/main/java/com/freepath/devpath/user/command/controller/UserCommandController.java
src/main/java/com/freepath/devpath/user/command/dto/UserCreateRequest.java
src/main/java/com/freepath/devpath/user/command/entity/User.java
src/main/java/com/freepath/devpath/user/command/entity/UserRole.java
src/main/java/com/freepath/devpath/user/command/repository/UserRepository.java
src/main/java/com/freepath/devpath/user/command/service/UserCommandService.java

feat: 일반 로그인 로그아웃 기능 구현

---

src/main/java/com/freepath/devpath/user/command/dto/UserCreateRequest.java

[fix #5] 유저 회원가입 DTO 수정

---

src/main/java/com/freepath/devpath/common/auth/controller/AuthController.java
src/main/java/com/freepath/devpath/common/auth/service/AuthService.java
src/main/java/com/freepath/devpath/common/exception/ErrorCode.java

bug: delete user 시 발생하는 오류 수정

---

src/main/java/com/freepath/devpath/common/exception/ErrorCode.java
src/main/java/com/freepath/devpath/interview/query/controller/InterviewQueryController.java
src/main/java/com/freepath/devpath/interview/query/dto/InterviewDetailDto.java
src/main/java/com/freepath/devpath/interview/query/dto/InterviewRoomDetailResponse.java
src/main/java/com/freepath/devpath/interview/query/exception/InterviewQueryAccessException.java
src/main/java/com/freepath/devpath/interview/query/exception/InterviewQueryHistoryNotFoundException.java
src/main/java/com/freepath/devpath/interview/query/exception/InterviewRoomQueryAccessException.java
src/main/java/com/freepath/devpath/interview/query/exception/InterviewRoomQueryCreationException.java
src/main/java/com/freepath/devpath/interview/query/exception/InterviewRoomQueryNotFoundException.java
src/main/java/com/freepath/devpath/interview/query/mapper/InterviewMapper.java
src/main/java/com/freepath/devpath/interview/query/service/InterviewQueryService.java
src/main/resources/mappers/interview/InterviewMapper.xml

feat: 면접 조회 기능 구현

---

src/main/java/com/freepath/devpath/board/post/command/controller/PostCommandController.java
src/main/java/com/freepath/devpath/board/post/command/service/PostCommandService.java
src/main/java/com/freepath/devpath/board/post/query/controller/PostQueryController.java
src/main/java/com/freepath/devpath/board/post/query/dto/request/PostSearchRequest.java
src/main/java/com/freepath/devpath/board/post/query/dto/response/CategoryListResponse.java
src/main/java/com/freepath/devpath/board/post/query/dto/response/CatetgoryDto.java
src/main/java/com/freepath/devpath/board/post/query/dto/response/PostDetailDto.java
src/main/java/com/freepath/devpath/board/post/query/dto/response/PostDetailResponse.java
src/main/java/com/freepath/devpath/board/post/query/dto/response/PostDto.java
src/main/java/com/freepath/devpath/board/post/query/dto/response/PostListResponse.java
src/main/java/com/freepath/devpath/board/post/query/exception/NoSuchPostException.java
src/main/java/com/freepath/devpath/board/post/query/mapper/PostMapper.java
src/main/java/com/freepath/devpath/board/post/query/service/PostQueryService.java
src/main/resources/mappers/board/postMapper.xml

feat: 게시물 조회, 카테고리 조회 기능 구현

---

src/main/java/com/freepath/devpath/common/config/SecurityConfig.java
src/main/java/com/freepath/devpath/user/command/controller/UserCommandController.java
src/main/java/com/freepath/devpath/user/query/controller/MyPageController.java
src/main/java/com/freepath/devpath/user/query/controller/UserQueryController.java
src/main/java/com/freepath/devpath/user/query/dto/request/UserInfoRequest.java
src/main/java/com/freepath/devpath/user/query/dto/response/UserInfoResponse.java
src/main/java/com/freepath/devpath/user/query/mapper/MyPageMapper.java
src/main/java/com/freepath/devpath/user/query/service/MyPageService.java
src/main/resources/mappers/chatting/ChattingRoomMapper.xml
src/main/resources/mappers/user/MyPageMapper.xml

feat: 마이페이지 내의 회원 정보 조회 기능 구현

---

src/main/java/com/freepath/devpath/board/post/command/controller/PostCommandController.java
src/main/java/com/freepath/devpath/board/post/command/dto/request/PostCreateRequest.java
src/main/java/com/freepath/devpath/board/post/command/dto/request/PostUpdateRequest.java
src/main/java/com/freepath/devpath/board/post/command/dto/response/PostCreateResponse.java
src/main/java/com/freepath/devpath/board/post/command/service/AttachmentService.java
src/main/java/com/freepath/devpath/board/post/command/service/PostCommandService.java
src/main/java/com/freepath/devpath/board/vote/command/dto/request/VoteCreateRequest.java
src/main/java/com/freepath/devpath/board/vote/command/entity/Vote.java
src/main/java/com/freepath/devpath/board/vote/command/entity/VoteItem.java
src/main/java/com/freepath/devpath/board/vote/command/repository/VoteItemRepository.java
src/main/java/com/freepath/devpath/board/vote/command/repository/VoteRepository.java
src/main/java/com/freepath/devpath/board/vote/command/service/VoteService.java

feat: 게시물 투표 등록 기능 구현

---

src/main/java/com/freepath/devpath/common/exception/ErrorCode.java
src/main/java/com/freepath/devpath/interview/command/application/controller/InterviewCommandController.java
src/main/java/com/freepath/devpath/interview/command/application/service/InterviewCommandService.java
src/main/java/com/freepath/devpath/interview/command/domain/repository/InterviewRepository.java
src/main/java/com/freepath/devpath/interview/command/exception/InterviewRoomDeleteException.java
src/main/java/com/freepath/devpath/interview/command/infrastructure/gpt/GptService.java
src/main/java/com/freepath/devpath/interview/query/controller/InterviewAdminQueryController.java
src/main/java/com/freepath/devpath/interview/query/controller/InterviewQueryController.java
src/main/java/com/freepath/devpath/interview/query/mapper/InterviewMapper.java
src/main/java/com/freepath/devpath/interview/query/service/InterviewQueryAdminService.java
src/main/java/com/freepath/devpath/interview/query/service/InterviewQueryService.java
src/main/resources/mappers/interview/InterviewMapper.xml

feat: 면접 추가 기능 구현

---

src/main/java/com/freepath/devpath/board/vote/command/controller/VoteController.java
src/main/java/com/freepath/devpath/board/vote/command/dto/request/VoteParticipateRequest.java
src/main/java/com/freepath/devpath/board/vote/command/entity/VoteHistory.java
src/main/java/com/freepath/devpath/board/vote/command/exception/VoteParticipateFailedException.java
src/main/java/com/freepath/devpath/board/vote/command/repository/VoteHistoryRepository.java
src/main/java/com/freepath/devpath/board/vote/command/service/VoteService.java
src/main/java/com/freepath/devpath/common/exception/ErrorCode.java

feat: 투표 참여 기능 구현

---

src/main/java/com/freepath/devpath/board/comment/query/controller/CommentQueryController.java
src/main/java/com/freepath/devpath/board/comment/query/dto/HierarchicalCommentDto.java
src/main/java/com/freepath/devpath/board/comment/query/dto/MyCommentListResponse.java
src/main/java/com/freepath/devpath/board/comment/query/dto/MyCommentSearchRequest.java
src/main/java/com/freepath/devpath/board/comment/query/mapper/CommentMapper.java
src/main/java/com/freepath/devpath/board/comment/query/service/CommentQueryService.java
src/main/java/com/freepath/devpath/email/command/application/Dto/NewsRequestDto.java
src/main/resources/mappers/comments/comment.xml

Feature/comment Paging Comment

---

src/main/java/com/freepath/devpath/board/vote/command/controller/VoteController.java
src/main/java/com/freepath/devpath/board/vote/command/entity/Vote.java
src/main/java/com/freepath/devpath/board/vote/command/exception/VoteEndFailedException.java
src/main/java/com/freepath/devpath/board/vote/command/repository/VoteRepository.java
src/main/java/com/freepath/devpath/board/vote/command/service/VoteService.java
src/main/java/com/freepath/devpath/common/exception/ErrorCode.java

feat: 투표 종료 기능 구현

---

src/main/java/com/freepath/devpath/interview/command/application/controller/InterviewCommandController.java
src/main/java/com/freepath/devpath/interview/command/application/dto/request/InterviewRoomCommandRequest.java
src/main/java/com/freepath/devpath/interview/command/application/dto/response/InterviewRoomCommandResponse.java
src/main/java/com/freepath/devpath/interview/command/application/service/InterviewCommandService.java
src/main/java/com/freepath/devpath/interview/command/domain/aggregate/InterviewRoom.java
src/main/java/com/freepath/devpath/interview/query/dto/InterviewRoomDetailResponse.java
src/main/java/com/freepath/devpath/interview/query/dto/InterviewRoomDto.java
src/main/java/com/freepath/devpath/interview/query/dto/InterviewSummaryResponse.java
src/main/java/com/freepath/devpath/interview/query/mapper/InterviewMapper.java
src/main/java/com/freepath/devpath/interview/query/service/InterviewQueryService.java
src/main/resources/mappers/interview/InterviewMapper.xml

feat: 면접방 테이블 변경된 구조 반영

---

build.gradle
src/main/java/com/freepath/devpath/board/post/command/domain/Attachment.java
src/main/java/com/freepath/devpath/board/post/command/domain/Board.java
src/main/java/com/freepath/devpath/board/post/command/domain/BoardDocument.java
src/main/java/com/freepath/devpath/board/post/command/repository/AttachmentRepository.java
src/main/java/com/freepath/devpath/board/post/command/repository/PostElasticRepository.java
src/main/java/com/freepath/devpath/board/post/command/repository/PostRepository.java
src/main/java/com/freepath/devpath/board/post/command/service/AttachmentService.java
src/main/java/com/freepath/devpath/board/post/command/service/PostCommandService.java
src/main/java/com/freepath/devpath/board/post/query/controller/PostQueryController.java
src/main/java/com/freepath/devpath/board/post/query/dto/request/PostContentSearchRequest.java
src/main/java/com/freepath/devpath/board/post/query/mapper/PostMapper.java
src/main/java/com/freepath/devpath/board/post/query/service/PostQueryService.java
src/main/java/com/freepath/devpath/common/config/ElasticsearchConfig.java
src/main/resources/application.yml
src/main/resources/mappers/board/PostMapper.xml

feat: 게시글 내용 검색 필터(ElasticSearch 적용)

---

src/main/java/com/freepath/devpath/chatting/command/application/service/ChattingRoomCommandService.java

fix: 패키지명 수정 리팩토링

---

src/main/java/com/freepath/devpath/common/auth/service/AuthService.java
src/main/java/com/freepath/devpath/common/jwt/OAuth2SuccessHandler.java
src/main/java/com/freepath/devpath/user/command/controller/UserCommandController.java
src/main/java/com/freepath/devpath/user/command/repository/UserCommandRepository.java
src/main/java/com/freepath/devpath/user/command/service/UserCommandService.java

feat: 일반, 구글 회원 중 제재된 회원 처리 기능 구현

---

src/main/java/com/freepath/devpath/common/auth/service/CustomUserDetailsService.java
src/main/java/com/freepath/devpath/report/domain/ReportCheck.java
src/main/java/com/freepath/devpath/report/repository/ReportCheckRepository.java
src/main/java/com/freepath/devpath/report/service/ReportService.java

refactor: 게시글, 댓글 신고 로직 수정

---

src/main/java/com/freepath/devpath/common/config/SecurityConfig.java
src/main/java/com/freepath/devpath/common/config/SwaggerConfig.java

swagger 테스트

---

src/main/java/com/freepath/devpath/interview/command/application/controller/InterviewCommandController.java
src/main/java/com/freepath/devpath/interview/command/application/dto/request/InterviewAnswerCommandRequest.java
src/main/java/com/freepath/devpath/interview/command/application/dto/request/InterviewRoomCommandRequest.java
src/main/java/com/freepath/devpath/interview/command/application/dto/response/InterviewRoomCommandResponse.java
src/main/java/com/freepath/devpath/interview/command/application/service/InterviewCommandService.java
src/main/java/com/freepath/devpath/interview/command/domain/aggregate/DifficultyLevel.java
src/main/java/com/freepath/devpath/interview/command/domain/aggregate/EvaluationStrictness.java
src/main/java/com/freepath/devpath/interview/command/domain/aggregate/InterviewRoom.java
src/main/java/com/freepath/devpath/interview/command/domain/aggregate/InterviewRoomStatus.java
src/main/java/com/freepath/devpath/interview/command/domain/repository/InterviewRoomRepository.java
src/main/java/com/freepath/devpath/interview/command/infrastructure/gpt/GptService.java
src/main/java/com/freepath/devpath/interview/command/infrastructure/scheduler/InterviewRoomExpirationScheduler.java
src/main/java/com/freepath/devpath/interview/query/controller/InterviewAdminQueryController.java
src/main/java/com/freepath/devpath/interview/query/controller/InterviewQueryController.java
src/main/java/com/freepath/devpath/interview/query/dto/InterviewRoomDetailResponse.java
src/main/java/com/freepath/devpath/interview/query/dto/InterviewRoomDto.java
src/main/java/com/freepath/devpath/interview/query/mapper/InterviewMapper.java
src/main/java/com/freepath/devpath/interview/query/service/InterviewQueryAdminService.java
src/main/java/com/freepath/devpath/interview/query/service/InterviewQueryService.java
src/main/resources/mappers/interview/InterviewMapper.xml

feat: 면접에 질문 난이도 및 평가 엄격도 반영

---

src/main/java/com/freepath/devpath/board/vote/command/controller/VoteCommandController.java
src/main/java/com/freepath/devpath/board/vote/query/controller/VoteQueryController.java

feat: 투표 컨택스트 Swagger 문서화 적용

---

src/main/java/com/freepath/devpath/report/controller/ReportController.java

feat: 유저 신고 컨택스트 Swagger 문서화 적용

---

src/main/java/com/freepath/devpath/interview/command/application/controller/InterviewCommandController.java
src/main/java/com/freepath/devpath/interview/command/application/service/InterviewCommandService.java
src/main/java/com/freepath/devpath/interview/command/domain/aggregate/Interview.java
src/main/java/com/freepath/devpath/interview/command/domain/aggregate/InterviewRole.java
src/main/java/com/freepath/devpath/interview/command/domain/aggregate/InterviewRoom.java
src/main/java/com/freepath/devpath/interview/command/domain/repository/InterviewRepository.java
src/main/java/com/freepath/devpath/interview/command/infrastructure/gpt/GptService.java
src/main/java/com/freepath/devpath/interview/query/controller/InterviewAdminQueryController.java
src/main/java/com/freepath/devpath/interview/query/controller/InterviewQueryController.java
src/main/java/com/freepath/devpath/interview/query/dto/InterviewRoomDetailResponse.java
src/main/java/com/freepath/devpath/interview/query/dto/ReexecutedRoomDto.java
src/main/java/com/freepath/devpath/interview/query/mapper/InterviewMapper.java
src/main/java/com/freepath/devpath/interview/query/service/InterviewQueryService.java
src/main/resources/mappers/interview/InterviewMapper.xml

feat: 면접방 재실행 기능 구현

---

src/main/java/com/freepath/devpath/common/config/SecurityConfig.java
src/main/java/com/freepath/devpath/user/command/controller/UserCommandController.java
src/main/java/com/freepath/devpath/user/command/dto/SaveDevMbti.java
src/main/java/com/freepath/devpath/user/command/entity/User.java
src/main/java/com/freepath/devpath/user/command/service/UserCommandService.java

feat: 개발자 성향 테스트 저장 기능 구현

---

src/main/resources/application.yml

refactor: swagger 태그명 정렬

---

src/main/java/com/freepath/devpath/chatting/command/domain/mongo/aggregate/Chatting.java

Chatting 도메인 snake_case 적용

---

src/main/java/com/freepath/devpath/interview/command/application/controller/InterviewCommandController.java
src/main/java/com/freepath/devpath/interview/query/controller/InterviewAdminQueryController.java
src/main/java/com/freepath/devpath/interview/query/controller/InterviewQueryController.java

refactor: swagger 태그명 통일

---

src/main/java/com/freepath/devpath/chatting/command/application/controller/ChattingCommandController.java
src/main/java/com/freepath/devpath/chatting/command/application/controller/ChattingRoomCommandController.java
src/main/java/com/freepath/devpath/chatting/command/application/controller/UserBlockCommandController.java
src/main/java/com/freepath/devpath/chatting/command/application/controller/WaitingRoomCommandController.java
src/main/java/com/freepath/devpath/chatting/query/controller/UserBlockQueryController.java

[refactor] chatting swagger 어노테이션 변경

---

devpath-community-server/src/main/java/com/freepath/devpath/email/command/application/Dto/EmailCheckDto.java
devpath-community-server/src/main/java/com/freepath/devpath/email/command/application/controller/EmailController.java
devpath/src/main/java/com/freepath/devpath/email/command/application/Dto/EmailCheckDto.java
devpath/src/main/java/com/freepath/devpath/email/command/application/controller/EmailController.java

refactor: EmailController, EmailCheckDto 어노테이션 수정

---

devpath/src/main/java/com/freepath/devpath/board/post/command/dto/request/PostCreateRequest.java
devpath/src/main/java/com/freepath/devpath/board/post/command/dto/request/PostUpdateRequest.java
devpath/src/main/java/com/freepath/devpath/board/post/command/dto/response/PostCreateResponse.java
devpath/src/main/java/com/freepath/devpath/board/vote/command/repository/VoteItemRepository.java
devpath/src/main/java/com/freepath/devpath/board/vote/command/repository/VoteRepository.java
devpath/src/test/java/com/freepath/devpath/board/post/command/controller/PostCommandControllerTest.java
devpath/src/test/java/com/freepath/devpath/board/post/command/service/PostCommandServiceIntegrationTest.java
devpath/src/test/java/com/freepath/devpath/board/post/command/service/PostCommandServiceTest.java

feat: 게시글 등록 테스트 코드 작성

---

devpath-feature-server/src/main/java/com/freepath/devpath/email/command/application/service/NewsService.java
devpath-feature-server/src/main/resources/application.yml

Feature 서버 IT 뉴스 서비스 수정

---

devpath-community-server/src/main/java/com/freepath/devpath/common/auth/controller/AuthController.java
devpath-community-server/src/main/java/com/freepath/devpath/common/auth/dto/LoginResponse.java
devpath-community-server/src/main/java/com/freepath/devpath/common/auth/service/AuthService.java

feat: 유저 로그인 시 response 값에 user role 값 추가

---

devpath/src/main/java/com/freepath/devpath/common/auth/controller/AuthController.java
devpath/src/main/java/com/freepath/devpath/common/auth/dto/LoginResponse.java
devpath/src/main/java/com/freepath/devpath/common/auth/service/AuthService.java

feat: community server 내용 반영

---

devpath/src/main/java/com/freepath/devpath/chatting/query/controller/ChattingRoomQueryController.java
devpath/src/main/java/com/freepath/devpath/chatting/query/dto/response/WaitingChattingRoomDTO.java
devpath/src/main/java/com/freepath/devpath/chatting/query/dto/response/WaitingChattingRoomResponse.java
devpath/src/main/java/com/freepath/devpath/chatting/query/mapper/ChattingRoomMapper.java
devpath/src/main/java/com/freepath/devpath/chatting/query/service/ChattingRoomQueryService.java
devpath/src/main/resources/mappers/chatting/ChattingRoomMapper.xml
devpath/src/main/resources/mappers/chatting/UserBlockMapper.xml

[fix #175] eureka server의 채팅 로직으로 최신화

---

devpath/src/main/java/com/freepath/devpath/interview/command/application/dto/response/InterviewAnswerCommandResponse.java
devpath/src/main/java/com/freepath/devpath/interview/command/application/service/InterviewCommandService.java
devpath/src/main/java/com/freepath/devpath/interview/command/domain/aggregate/InterviewRoom.java
devpath/src/main/java/com/freepath/devpath/interview/query/dto/InterviewRoomDetailResponse.java
devpath/src/main/java/com/freepath/devpath/interview/query/dto/InterviewRoomDto.java
devpath/src/main/java/com/freepath/devpath/interview/query/service/InterviewQueryService.java
devpath/src/main/resources/mappers/interview/InterviewMapper.xml

feat: 모의 면접 API 수정

---

devpath/src/main/java/com/freepath/devpath/common/config/WebConfig.java
devpath/src/main/java/com/freepath/devpath/common/jwt/OAuth2SuccessHandler.java

[feat] WebConfig 파일 추가, OAuth2SuccessHandler.java 내용 수정

---

devpath/src/main/java/com/freepath/devpath/common/jwt/OAuth2SuccessHandler.java

[feat] OAuth2SuccessHandler.java 내용 수정

---

devpath/src/main/java/com/freepath/devpath/common/config/SecurityConfig.java

featj: DevTI 결과 비회원 접속 허용

---

devpath/src/main/resources/mappers/chatting/ChattingRoomMapper.xml

[fix #184] 채팅에 참여중인 회원 조회 로직 수정

---

devpath/src/main/java/com/freepath/devpath/user/query/dto/response/UserInfoResponse.java
devpath/src/main/resources/mappers/user/MyPageMapper.xml

[feat] 마이페이지 유저 정보 조회 수정

---

devpath/src/main/java/com/freepath/devpath/chatting/command/application/controller/WaitingRoomCommandController.java
devpath/src/main/java/com/freepath/devpath/chatting/command/application/service/WaitingRoomCommandService.java

[fix #188] 게시글 기준으로 그룹채팅방 참여 요청하게 수정

---

devpath/src/main/java/com/freepath/devpath/common/auth/dto/LoginResponse.java
devpath/src/main/java/com/freepath/devpath/common/auth/service/AuthService.java

[fix #192] LoginResponse 필드 추가 및 AuthService 코드 수정

---

devpath/src/main/java/com/freepath/devpath/interview/query/controller/InterviewAdminQueryController.java
devpath/src/main/java/com/freepath/devpath/interview/query/controller/InterviewQueryController.java
devpath/src/main/java/com/freepath/devpath/interview/query/mapper/InterviewMapper.java
devpath/src/main/java/com/freepath/devpath/interview/query/service/InterviewQueryAdminService.java
devpath/src/main/java/com/freepath/devpath/interview/query/service/InterviewQueryService.java
devpath/src/main/resources/mappers/interview/InterviewMapper.xml

feat: 모의 면접 정렬/필터 api 수정

---

devpath/src/main/java/com/freepath/devpath/board/comment/query/dto/CommentTreeDto.java
devpath/src/main/java/com/freepath/devpath/board/comment/query/dto/HierarchicalCommentDto.java
devpath/src/main/java/com/freepath/devpath/board/comment/query/service/CommentQueryService.java
devpath/src/main/resources/mappers/board/PostMapper.xml
devpath/src/main/resources/mappers/comments/comment.xml

[fix #199] userId 값을 받아오도록 필드 추가, mapper 수정

---

devpath/src/main/java/com/freepath/devpath/common/jwt/OAuth2SuccessHandler.java

[feat] 구글 로그인 처리

---

devpath/src/main/java/com/freepath/devpath/interview/query/dto/InterviewRoomDto.java
devpath/src/main/resources/mappers/interview/InterviewMapper.xml

style: 면접방 목록 필터 조회 dto 수정

---

devpath/src/main/java/com/freepath/devpath/chatting/command/application/service/ChattingRoomCommandService.java

createChattingRoom 로직 수정

---

devpath/src/main/java/com/freepath/devpath/common/auth/dto/UserDeleteRequest.java

feat: 회원 탈퇴 부분 코드 수정

---

devpath/src/main/java/com/freepath/devpath/common/config/SecurityConfig.java

[feat] 스프링시큐리티에 코드 추가
